// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frc/team3171/protos/auton_data.proto

// Protobuf Java Version: 3.25.3
package frc.team3171.protos;

public final class AutonData {
  private AutonData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_frc_team3171_protos_AutonTimestampData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_frc_team3171_protos_AutonTimestampData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_frc_team3171_protos_AutonRecorderData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_frc_team3171_protos_AutonRecorderData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$frc/team3171/protos/auton_data.proto\022\023" +
      "frc.team3171.protos\032/frc/team3171/protos" +
      "/xbox_controller_state.proto\"\273\001\n\022AutonTi" +
      "mestampData\022\021\n\ttimestamp\030\001 \001(\001\022G\n\025driver" +
      "ControllerState\030\002 \001(\0132(.frc.team3171.pro" +
      "tos.XboxControllerState\022I\n\027operatorContr" +
      "ollerState\030\003 \001(\0132(.frc.team3171.protos.X" +
      "boxControllerState\"J\n\021AutonRecorderData\022" +
      "5\n\004data\030\001 \003(\0132\'.frc.team3171.protos.Auto" +
      "nTimestampDataB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          frc.team3171.protos.XboxControllerStateOuterClass.getDescriptor(),
        });
    internal_static_frc_team3171_protos_AutonTimestampData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_frc_team3171_protos_AutonTimestampData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_frc_team3171_protos_AutonTimestampData_descriptor,
        new java.lang.String[] { "Timestamp", "DriverControllerState", "OperatorControllerState", });
    internal_static_frc_team3171_protos_AutonRecorderData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_frc_team3171_protos_AutonRecorderData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_frc_team3171_protos_AutonRecorderData_descriptor,
        new java.lang.String[] { "Data", });
    frc.team3171.protos.XboxControllerStateOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
