// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frc/team3171/protos/auton_data.proto

// Protobuf Java Version: 3.25.3
package frc.team3171.protos;

public interface AutonTimestampDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:frc.team3171.protos.AutonTimestampData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double timestamp = 1;</code>
   * @return The timestamp.
   */
  double getTimestamp();

  /**
   * <code>.frc.team3171.protos.XboxControllerState driverControllerState = 2;</code>
   * @return Whether the driverControllerState field is set.
   */
  boolean hasDriverControllerState();
  /**
   * <code>.frc.team3171.protos.XboxControllerState driverControllerState = 2;</code>
   * @return The driverControllerState.
   */
  frc.team3171.protos.XboxControllerState getDriverControllerState();
  /**
   * <code>.frc.team3171.protos.XboxControllerState driverControllerState = 2;</code>
   */
  frc.team3171.protos.XboxControllerStateOrBuilder getDriverControllerStateOrBuilder();

  /**
   * <code>.frc.team3171.protos.XboxControllerState operatorControllerState = 3;</code>
   * @return Whether the operatorControllerState field is set.
   */
  boolean hasOperatorControllerState();
  /**
   * <code>.frc.team3171.protos.XboxControllerState operatorControllerState = 3;</code>
   * @return The operatorControllerState.
   */
  frc.team3171.protos.XboxControllerState getOperatorControllerState();
  /**
   * <code>.frc.team3171.protos.XboxControllerState operatorControllerState = 3;</code>
   */
  frc.team3171.protos.XboxControllerStateOrBuilder getOperatorControllerStateOrBuilder();
}
