// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frc/team3171/protos/auton_data.proto

// Protobuf Java Version: 3.25.3
package frc.team3171.protos;

public interface AutonRecorderDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:frc.team3171.protos.AutonRecorderData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .frc.team3171.protos.AutonTimestampData data = 1;</code>
   */
  java.util.List<frc.team3171.protos.AutonTimestampData> 
      getDataList();
  /**
   * <code>repeated .frc.team3171.protos.AutonTimestampData data = 1;</code>
   */
  frc.team3171.protos.AutonTimestampData getData(int index);
  /**
   * <code>repeated .frc.team3171.protos.AutonTimestampData data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .frc.team3171.protos.AutonTimestampData data = 1;</code>
   */
  java.util.List<? extends frc.team3171.protos.AutonTimestampDataOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .frc.team3171.protos.AutonTimestampData data = 1;</code>
   */
  frc.team3171.protos.AutonTimestampDataOrBuilder getDataOrBuilder(
      int index);
}
