// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frc/team3171/protos/slew_drive.proto

// Protobuf Java Version: 3.25.3
package frc.team3171.protos;

public final class SlewDrive {
  private SlewDrive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_frc_team3171_protos_SlewCalibration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_frc_team3171_protos_SlewCalibration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$frc/team3171/protos/slew_drive.proto\022\023" +
      "frc.team3171.protos\"\205\001\n\017SlewCalibration\022" +
      "\033\n\023leftFrontSlewOffset\030\001 \001(\001\022\032\n\022leftRear" +
      "SlewOffset\030\002 \001(\001\022\034\n\024rightFrontSlewOffset" +
      "\030\003 \001(\001\022\033\n\023rightRearSlewOffset\030\004 \001(\001B\002P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_frc_team3171_protos_SlewCalibration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_frc_team3171_protos_SlewCalibration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_frc_team3171_protos_SlewCalibration_descriptor,
        new java.lang.String[] { "LeftFrontSlewOffset", "LeftRearSlewOffset", "RightFrontSlewOffset", "RightRearSlewOffset", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
