// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frc/team3171/protos/slew_drive.proto

// Protobuf Java Version: 3.25.3
package frc.team3171.protos;

public interface SlewCalibrationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:frc.team3171.protos.SlewCalibration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double leftFrontSlewOffset = 1;</code>
   * @return The leftFrontSlewOffset.
   */
  double getLeftFrontSlewOffset();

  /**
   * <code>double leftRearSlewOffset = 2;</code>
   * @return The leftRearSlewOffset.
   */
  double getLeftRearSlewOffset();

  /**
   * <code>double rightFrontSlewOffset = 3;</code>
   * @return The rightFrontSlewOffset.
   */
  double getRightFrontSlewOffset();

  /**
   * <code>double rightRearSlewOffset = 4;</code>
   * @return The rightRearSlewOffset.
   */
  double getRightRearSlewOffset();
}
