// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frc/team3171/protos/xbox_controller_state.proto

// Protobuf Java Version: 3.25.3
package frc.team3171.protos;

public interface XboxControllerStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:frc.team3171.protos.XboxControllerState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double leftX = 1;</code>
   * @return Whether the leftX field is set.
   */
  boolean hasLeftX();
  /**
   * <code>optional double leftX = 1;</code>
   * @return The leftX.
   */
  double getLeftX();

  /**
   * <code>optional double leftY = 2;</code>
   * @return Whether the leftY field is set.
   */
  boolean hasLeftY();
  /**
   * <code>optional double leftY = 2;</code>
   * @return The leftY.
   */
  double getLeftY();

  /**
   * <code>optional double rightX = 3;</code>
   * @return Whether the rightX field is set.
   */
  boolean hasRightX();
  /**
   * <code>optional double rightX = 3;</code>
   * @return The rightX.
   */
  double getRightX();

  /**
   * <code>optional double rightY = 4;</code>
   * @return Whether the rightY field is set.
   */
  boolean hasRightY();
  /**
   * <code>optional double rightY = 4;</code>
   * @return The rightY.
   */
  double getRightY();

  /**
   * <code>optional double leftTriggerAxis = 5;</code>
   * @return Whether the leftTriggerAxis field is set.
   */
  boolean hasLeftTriggerAxis();
  /**
   * <code>optional double leftTriggerAxis = 5;</code>
   * @return The leftTriggerAxis.
   */
  double getLeftTriggerAxis();

  /**
   * <code>optional double rightTriggerAxis = 6;</code>
   * @return Whether the rightTriggerAxis field is set.
   */
  boolean hasRightTriggerAxis();
  /**
   * <code>optional double rightTriggerAxis = 6;</code>
   * @return The rightTriggerAxis.
   */
  double getRightTriggerAxis();

  /**
   * <code>optional int32 pov = 7;</code>
   * @return Whether the pov field is set.
   */
  boolean hasPov();
  /**
   * <code>optional int32 pov = 7;</code>
   * @return The pov.
   */
  int getPov();

  /**
   * <code>optional bool aButton = 8;</code>
   * @return Whether the aButton field is set.
   */
  boolean hasAButton();
  /**
   * <code>optional bool aButton = 8;</code>
   * @return The aButton.
   */
  boolean getAButton();

  /**
   * <code>optional bool bButton = 9;</code>
   * @return Whether the bButton field is set.
   */
  boolean hasBButton();
  /**
   * <code>optional bool bButton = 9;</code>
   * @return The bButton.
   */
  boolean getBButton();

  /**
   * <code>optional bool xButton = 10;</code>
   * @return Whether the xButton field is set.
   */
  boolean hasXButton();
  /**
   * <code>optional bool xButton = 10;</code>
   * @return The xButton.
   */
  boolean getXButton();

  /**
   * <code>optional bool yButton = 11;</code>
   * @return Whether the yButton field is set.
   */
  boolean hasYButton();
  /**
   * <code>optional bool yButton = 11;</code>
   * @return The yButton.
   */
  boolean getYButton();

  /**
   * <code>optional bool startButton = 12;</code>
   * @return Whether the startButton field is set.
   */
  boolean hasStartButton();
  /**
   * <code>optional bool startButton = 12;</code>
   * @return The startButton.
   */
  boolean getStartButton();

  /**
   * <code>optional bool backButton = 13;</code>
   * @return Whether the backButton field is set.
   */
  boolean hasBackButton();
  /**
   * <code>optional bool backButton = 13;</code>
   * @return The backButton.
   */
  boolean getBackButton();

  /**
   * <code>optional bool leftBumper = 14;</code>
   * @return Whether the leftBumper field is set.
   */
  boolean hasLeftBumper();
  /**
   * <code>optional bool leftBumper = 14;</code>
   * @return The leftBumper.
   */
  boolean getLeftBumper();

  /**
   * <code>optional bool rightBumper = 15;</code>
   * @return Whether the rightBumper field is set.
   */
  boolean hasRightBumper();
  /**
   * <code>optional bool rightBumper = 15;</code>
   * @return The rightBumper.
   */
  boolean getRightBumper();

  /**
   * <code>optional bool leftStickButton = 16;</code>
   * @return Whether the leftStickButton field is set.
   */
  boolean hasLeftStickButton();
  /**
   * <code>optional bool leftStickButton = 16;</code>
   * @return The leftStickButton.
   */
  boolean getLeftStickButton();

  /**
   * <code>optional bool rightStickButton = 17;</code>
   * @return Whether the rightStickButton field is set.
   */
  boolean hasRightStickButton();
  /**
   * <code>optional bool rightStickButton = 17;</code>
   * @return The rightStickButton.
   */
  boolean getRightStickButton();
}
