// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frc/team3171/protos/xbox_controller_state.proto

// Protobuf Java Version: 3.25.3
package frc.team3171.protos;

public final class XboxControllerStateOuterClass {
  private XboxControllerStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_frc_team3171_protos_XboxControllerState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_frc_team3171_protos_XboxControllerState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/frc/team3171/protos/xbox_controller_st" +
      "ate.proto\022\023frc.team3171.protos\"\243\005\n\023XboxC" +
      "ontrollerState\022\022\n\005leftX\030\001 \001(\001H\000\210\001\001\022\022\n\005le" +
      "ftY\030\002 \001(\001H\001\210\001\001\022\023\n\006rightX\030\003 \001(\001H\002\210\001\001\022\023\n\006r" +
      "ightY\030\004 \001(\001H\003\210\001\001\022\034\n\017leftTriggerAxis\030\005 \001(" +
      "\001H\004\210\001\001\022\035\n\020rightTriggerAxis\030\006 \001(\001H\005\210\001\001\022\020\n" +
      "\003pov\030\007 \001(\005H\006\210\001\001\022\024\n\007aButton\030\010 \001(\010H\007\210\001\001\022\024\n" +
      "\007bButton\030\t \001(\010H\010\210\001\001\022\024\n\007xButton\030\n \001(\010H\t\210\001" +
      "\001\022\024\n\007yButton\030\013 \001(\010H\n\210\001\001\022\030\n\013startButton\030\014" +
      " \001(\010H\013\210\001\001\022\027\n\nbackButton\030\r \001(\010H\014\210\001\001\022\027\n\nle" +
      "ftBumper\030\016 \001(\010H\r\210\001\001\022\030\n\013rightBumper\030\017 \001(\010" +
      "H\016\210\001\001\022\034\n\017leftStickButton\030\020 \001(\010H\017\210\001\001\022\035\n\020r" +
      "ightStickButton\030\021 \001(\010H\020\210\001\001B\010\n\006_leftXB\010\n\006" +
      "_leftYB\t\n\007_rightXB\t\n\007_rightYB\022\n\020_leftTri" +
      "ggerAxisB\023\n\021_rightTriggerAxisB\006\n\004_povB\n\n" +
      "\010_aButtonB\n\n\010_bButtonB\n\n\010_xButtonB\n\n\010_yB" +
      "uttonB\016\n\014_startButtonB\r\n\013_backButtonB\r\n\013" +
      "_leftBumperB\016\n\014_rightBumperB\022\n\020_leftStic" +
      "kButtonB\023\n\021_rightStickButtonB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_frc_team3171_protos_XboxControllerState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_frc_team3171_protos_XboxControllerState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_frc_team3171_protos_XboxControllerState_descriptor,
        new java.lang.String[] { "LeftX", "LeftY", "RightX", "RightY", "LeftTriggerAxis", "RightTriggerAxis", "Pov", "AButton", "BButton", "XButton", "YButton", "StartButton", "BackButton", "LeftBumper", "RightBumper", "LeftStickButton", "RightStickButton", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
